"""add profile_image

Revision ID: 989069ab2899
Revises: dd57eb23ba2d
Create Date: 2026-01-16 15:05:39.718675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989069ab2899'
down_revision: Union[str, Sequence[str], None] = 'dd57eb23ba2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
